# Generated by Django 6.0.6 on 2026-06-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcanela', '0004_producto_alter_pedido_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.CharField(blank=True, default='', help_text='Nombre del archivo en static/appcanela/img/ (ej: clasico.png)', max_length=120),
        ),
    ]
