# Generated by Django 6.0.6 on 2026-06-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcanela', '0006_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilcliente',
            name='tarjeta_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfilcliente',
            name='tarjeta_ultimos4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='perfilcliente',
            name='tarjeta_vencimiento',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
