# Generated by Django 6.0.6 on 2026-06-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcanela', '0007_perfilcliente_tarjeta_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='correo_invitado',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion_entrega',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
