# Generated by Django 6.0.6 on 2026-06-24 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcanela', '0010_configuraciontienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuraciontienda',
            name='hora_apertura',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='configuraciontienda',
            name='hora_cierre',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('preparando', 'Preparando'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
