# Generated by Django 6.0.6 on 2026-06-24 03:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcanela', '0008_pedido_correo_invitado_pedido_direccion_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50000)]),
        ),
    ]
