# Generated by Django 6.0.6 on 2026-06-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcanela', '0009_alter_producto_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_apertura', models.TimeField(default='09:00')),
                ('hora_cierre', models.TimeField(default='18:00')),
                ('atiende_lunes', models.BooleanField(default=True)),
                ('atiende_martes', models.BooleanField(default=True)),
                ('atiende_miercoles', models.BooleanField(default=True)),
                ('atiende_jueves', models.BooleanField(default=True)),
                ('atiende_viernes', models.BooleanField(default=True)),
                ('atiende_sabado', models.BooleanField(default=True)),
                ('atiende_domingo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Configuración de la tienda',
                'verbose_name_plural': 'Configuración de la tienda',
            },
        ),
    ]
